# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../../test/mqtt_listener/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1069, 589)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 671, 80))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 54, 18))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(160, 30, 54, 18))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(350, 30, 54, 18))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(490, 30, 61, 18))
        self.label_4.setObjectName("label_4")
        self.broker_ipaddr = QtWidgets.QLineEdit(self.groupBox)
        self.broker_ipaddr.setGeometry(QtCore.QRect(30, 30, 113, 26))
        self.broker_ipaddr.setObjectName("broker_ipaddr")
        self.broker_port = QtWidgets.QLineEdit(self.groupBox)
        self.broker_port.setGeometry(QtCore.QRect(200, 30, 51, 26))
        self.broker_port.setObjectName("broker_port")
        self.user = QtWidgets.QLineEdit(self.groupBox)
        self.user.setGeometry(QtCore.QRect(420, 30, 51, 26))
        self.user.setObjectName("user")
        self.password = QtWidgets.QLineEdit(self.groupBox)
        self.password.setGeometry(QtCore.QRect(570, 30, 91, 26))
        self.password.setObjectName("password")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 90, 671, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.CB_carrier_common = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_carrier_common.setGeometry(QtCore.QRect(20, 30, 211, 24))
        self.CB_carrier_common.setObjectName("CB_carrier_common")
        self.CB_carrier_session = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_carrier_session.setGeometry(QtCore.QRect(20, 60, 211, 24))
        self.CB_carrier_session.setObjectName("CB_carrier_session")
        self.CB_system_common = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_system_common.setGeometry(QtCore.QRect(240, 30, 221, 24))
        self.CB_system_common.setObjectName("CB_system_common")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(500, 40, 41, 18))
        self.label_5.setObjectName("label_5")
        self.vehicle_no = QtWidgets.QLineEdit(self.groupBox_2)
        self.vehicle_no.setGeometry(QtCore.QRect(570, 30, 91, 26))
        self.vehicle_no.setObjectName("vehicle_no")
        self.CB_carrier_status1 = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_carrier_status1.setGeometry(QtCore.QRect(20, 90, 211, 24))
        self.CB_carrier_status1.setObjectName("CB_carrier_status1")
        self.CB_system_lastwill = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_system_lastwill.setGeometry(QtCore.QRect(240, 120, 221, 24))
        self.CB_system_lastwill.setObjectName("CB_system_lastwill")
        self.CB_system_session = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_system_session.setGeometry(QtCore.QRect(240, 60, 221, 24))
        self.CB_system_session.setObjectName("CB_system_session")
        self.CB_system_status = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_system_status.setGeometry(QtCore.QRect(240, 90, 221, 24))
        self.CB_system_status.setObjectName("CB_system_status")
        self.CB_carrier_status2 = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_carrier_status2.setGeometry(QtCore.QRect(20, 120, 211, 24))
        self.CB_carrier_status2.setObjectName("CB_carrier_status2")
        self.CB_carrier_lastwill = QtWidgets.QCheckBox(self.groupBox_2)
        self.CB_carrier_lastwill.setGeometry(QtCore.QRect(20, 150, 171, 24))
        self.CB_carrier_lastwill.setObjectName("CB_carrier_lastwill")
        self.Button_connect = QtWidgets.QPushButton(self.groupBox_2)
        self.Button_connect.setGeometry(QtCore.QRect(570, 110, 80, 26))
        self.Button_connect.setObjectName("Button_connect")
        self.tableWidget = QtWidgets.QTableWidget(self.centralWidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 280, 661, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(690, 10, 371, 111))
        self.groupBox_3.setObjectName("groupBox_3")
        self.MotionInfoButton = QtWidgets.QPushButton(self.groupBox_3)
        self.MotionInfoButton.setGeometry(QtCore.QRect(10, 30, 80, 26))
        self.MotionInfoButton.setObjectName("MotionInfoButton")
        self.MotionTaskButton = QtWidgets.QPushButton(self.groupBox_3)
        self.MotionTaskButton.setGeometry(QtCore.QRect(10, 70, 80, 26))
        self.MotionTaskButton.setObjectName("MotionTaskButton")
        self.LiftInfoButton = QtWidgets.QPushButton(self.groupBox_3)
        self.LiftInfoButton.setGeometry(QtCore.QRect(100, 30, 80, 26))
        self.LiftInfoButton.setObjectName("LiftInfoButton")
        self.LiftTaskButton = QtWidgets.QPushButton(self.groupBox_3)
        self.LiftTaskButton.setGeometry(QtCore.QRect(100, 70, 80, 26))
        self.LiftTaskButton.setObjectName("LiftTaskButton")
        self.PalletTaskButton = QtWidgets.QPushButton(self.groupBox_3)
        self.PalletTaskButton.setGeometry(QtCore.QRect(190, 30, 80, 26))
        self.PalletTaskButton.setObjectName("PalletTaskButton")
        self.MAButton = QtWidgets.QPushButton(self.centralWidget)
        self.MAButton.setGeometry(QtCore.QRect(700, 150, 80, 26))
        self.MAButton.setObjectName("MAButton")
        self.MAEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.MAEdit.setGeometry(QtCore.QRect(810, 150, 81, 26))
        self.MAEdit.setObjectName("MAEdit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1069, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Broker"))
        self.label.setText(_translate("MainWindow", "IP:"))
        self.label_2.setText(_translate("MainWindow", "Port:"))
        self.label_3.setText(_translate("MainWindow", "User:"))
        self.label_4.setText(_translate("MainWindow", "Password:"))
        self.groupBox_2.setTitle(_translate("MainWindow", " Topics"))
        self.CB_carrier_common.setText(_translate("MainWindow", "ZJ/Carrier/Commom/XX%06d"))
        self.CB_carrier_session.setText(_translate("MainWindow", "ZJ/Carrier/Session/N%04d"))
        self.CB_system_common.setText(_translate("MainWindow", "ZJ/System/Commom/XX%06d"))
        self.label_5.setText(_translate("MainWindow", "车号:"))
        self.CB_carrier_status1.setText(_translate("MainWindow", "ZJ/Carrier/Status1/N%04d"))
        self.CB_system_lastwill.setText(_translate("MainWindow", "ZJ/System/LastWill"))
        self.CB_system_session.setText(_translate("MainWindow", "ZJ/System/Session/N%04d"))
        self.CB_system_status.setText(_translate("MainWindow", "ZJ/System/Status"))
        self.CB_carrier_status2.setText(_translate("MainWindow", "ZJ/Carrier/Status2/N%04d"))
        self.CB_carrier_lastwill.setText(_translate("MainWindow", "ZJ/Carrier/LastWill"))
        self.Button_connect.setText(_translate("MainWindow", "连接"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "主题"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "类型"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "方向"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "内容"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Debug"))
        self.MotionInfoButton.setText(_translate("MainWindow", "运动信息"))
        self.MotionTaskButton.setText(_translate("MainWindow", "运动任务"))
        self.LiftInfoButton.setText(_translate("MainWindow", "举升信息"))
        self.LiftTaskButton.setText(_translate("MainWindow", "举升任务"))
        self.PalletTaskButton.setText(_translate("MainWindow", "托盘任务"))
        self.MAButton.setText(_translate("MainWindow", "手自动自定义"))


